"""added image to listing model and changed default profile image for user model

Revision ID: 14a691c9dce8
Revises: d3da7f1d5fa9
Create Date: 2025-11-23 22:17:02.928654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a691c9dce8'
down_revision: Union[str, Sequence[str], None] = 'd3da7f1d5fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_table', sa.Column('image', sa.String(), server_default="images/listings/placeholder.jpg", nullable=True))
    op.alter_column('user', 'profile_picture', server_default="images/profile/GatorAvatarTemporary.png", existing_type=sa.String(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_table', 'image')
    # ### end Alembic commands ###
